export const MESSAGES_LOAD = 'MESSAGES_LOAD'
export const MESSAGES_LOAD_SUCCESS = 'MESSAGES_LOAD_SUCCESS'
export const MESSAGES_LOAD_FAILURE = 'MESSAGES_LOAD_FAILURE'
export const MESSAGES_NEXT = 'MESSAGES_NEXT'
export const MESSAGES_EVENT = 'MESSAGES_EVENT'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_REGISTER = "USER_REGISTER"
export const USER_LOGOUT = "USER_LOGOUT"
